language: node_js
node_js:
    - "8.9.1"

stages:
    - security-tests
    - unit-tests

matrix:
    fast_finish: true
    allow_failures:
          - script:
              - npm outdated

jobs:
    include:
        - stage: security-tests
          script:
              - npm outdated

        - stage: security-tests
          script:
              - npm run security

        - stage: unit-tests
          script:
              - npm run test
